# run netcorewa3-linux on the bridge network
services:
  netcorewa3-linux:
    image: netcorewa3-linux:latest
    build:
      context: .
      dockerfile: ./linux/Dockerfile
    container_name: netcorewa3-linux
    restart: always
    network_mode: bridge
    ports:
      - 8080:8080
    volumes:
      - /var/log/netcorewa3-linux:/var/log/netcorewa3-linux
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  # run nginx on port 3000
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: always
#    network_mode: bridge
#    ports:
#    - 3000:80
#    volumes:
#    - /etc/localtime:/etc/localtime:ro

