# run netcorewa3-linux on the bridge network
services:
  netcorewa3-linux:
    image: ncwl
    build:
      context: .
      dockerfile: ./linux/Dockerfile
      
    container_name: ncwl
    restart: always
    network_mode: bridge
    ports:
      - 5000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

#  aspnet-sample:
#    image: mcr.microsoft.com/dotnet/samples:aspnetapp
#    container_name: aspnet-sample
#    restart: always
#    network_mode: bridge
#    ports:
#      - 5001:80
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    
