# run netcorewa3-linux on the bridge network
services:
  netcorewa3-linux:
    image: netcorewa3-linux
    build:
      context: .
      dockerfile: ./linux/Dockerfile
    container_name: netcorewa3-linux
    restart: always
    network_mode: host
    ports:
      - 5000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://localhost
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: always
#    network_mode: host
#    ports:
#    - 3000:80
#    volumes:
#    - /etc/localtime:/etc/localtime:ro

