name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  
  build-windows:
    
    env:
      FULL_IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-windows

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ FULL_IMAGE_NAME }}
          
      - name: Build the Docker image
        run: |
          docker build `
            --file Dockerfile `
            --tag "${{ FULL_IMAGE_NAME }}:latest" `
            --tag "${{ FULL_IMAGE_NAME }}:${{ github.sha }}" `
            .

      - name: Push the Docker image
        run: |
          docker push "${{ FULL_IMAGE_NAME }}:latest"
          docker push "${{ FULL_IMAGE_NAME }}:${{ github.sha }}"
      

  build-linux:

    runs-on: ubuntu-latest

    env:  
      FULL_IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ FULL_IMAGE_NAME }}
        
      - name: Build and push image to ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.linux
          push: true
          tags: ${{ FULL_IMAGE_NAME }}:latest, ${{ FULL_IMAGE_NAME }}:${{ github.sha }}
      