name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build-windows:

    runs-on: windows-latest

    env:
      IMAGE_NAME: willmitchell/netcorewa3

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push the Docker image
        run: docker push $IMAGE_NAME:latest

  build-linux:

    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: willmitchell/netcorewa3-linux

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile.linux --tag $IMAGE_NAME:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push $IMAGE_NAME:latest
        