name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag willmitchell/netcorewa3:latest
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push the Docker image
        run: docker push willmitchell/netcorewa3:latest
        
#      - name: Deploy to Azure
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: netcorewa3
#          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6b9b4b9c1c1c4c3c9b9b4b9c1c1c4c3c }}
#          package: willmitchell/netcorewa3:$(date +%s)
      
      