name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  VERSION: 0.2.0

jobs:
  
  build-windows:

    runs-on: windows-latest

    env:
      IMAGE_NAME: willmitchell/netcorewa3

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        # use pwsh syntax
        run: |
          docker build `
            --file Dockerfile `
            --tag "${env:IMAGE_NAME}:latest" `
            --tag "${env:IMAGE_NAME}:${{ github.sha }}" `
            --build-arg BUILD_DATE=$(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ") `
            --build-arg VCS_REF=${{ github.sha }} `
            --build-arg VERSION=${{ env.VERSION }} .
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push the Docker image
        run: |
          docker push $env:IMAGE_NAME:latest
          docker push $env:IMAGE_NAME:${{ github.sha }}

  build-linux:

    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: willmitchell/netcorewa3-linux

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image        
        run: |
          docker build \
            --file Dockerfile.linux \
            --tag $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:${{ github.sha }} \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=${{ github.sha }} \
            --build-arg VERSION=${{ env.VERSION }} .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

